apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortepix-java
  labels:
    app: fortepix-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortepix-java
  template:
    metadata:
      labels:
        app: fortepix-java
    spec:
      containers:
        - name: fortepix-java
          image: gcr.io/SEU_PROJETO/fortepix-java:beta
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: fortepix-db-secret
                  key: db_url
